version: 2.1
orbs:
  slack: circleci/slack@4.10.1

executors:
  openjdk-11:
    docker:
      - image: cimg/openjdk:11.0.17
    working_directory: ~/repo

jobs:
  branches:
    executor: openjdk-11
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn clean package -P branches,unit-tests

      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  develop:
    executor: openjdk-11
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn clean package -P unit-tests,sources

      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  rc:
    executor: openjdk-11
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn clean package -P unit-tests,integration-tests,sources

      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  tag:
    executor: openjdk-11
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn clean package -P sources,javadoc

      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

  deploy:
    executor: openjdk-11
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - attach_workspace:
          at: .

      - run: echo -e $GPG_KEY | gpg --import --no-tty --batch --yes

      - run: mvn deploy -s .circleci/settings.xml -P sources,javadoc -DskipTest=true

      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1

workflows:
  version: 2
  branches:
    jobs:
      - branches:
          filters:
            branches:
              ignore:
                - /rc-.*/
                - develop
                - master
  release-candidate:
    jobs:
      - rc:
          filters:
            branches:
              only:
                - /rc-.*/
      - deploy:
          requires:
            - rc
  develop:
    jobs:
      - develop:
          filters:
            branches:
              only:
                - develop
      - deploy:
          requires:
            - develop

  release:
    jobs:
      - tag:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - tag
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
