version: 2.1

executors:
  jdk-8:
    docker:
      - image: circleci/openjdk:8-jdk

jobs:
  build:
    executor: jdk-8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-
      - run: mvn dependency:go-offline
      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run: mvn clean install

workflows:
  version: 2
  build:
    jobs:
      - build