version: 2.1

executors:
  jdk-8:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - run: mvn dependency:go-offline

      - save_cache:
          key: m2-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn clean install

      # Save built artifacts
      - run: |
          set -xu
          mkdir -p artifacts
          cp -r target/*.jar artifacts/

      - store_artifacts:
          path: artifacts
          destination: jars

      - persist_to_workspace:
          root: .
          paths:
            - target

  deploy-snapshot:
    executor: jdk-8
    steps:
      - checkout

      - restore_cache:
          keys:
            - m2-{{ checksum "pom.xml" }}
            - m2-

      - attach_workspace:
          at: .

      - run: echo -e $GPG_KEY | gpg --import --no-tty --batch --yes

      - run: mvn deploy -s .circleci/settings.xml -DskipTest=true

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-snapshot:
          requires:
            - build
          filters:
            branches:
              only:
                - /^release.*/
